version: "3.7"

services:
  project_service:
    build:
      context: .
      dockerfile: ProjectAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    networks:
      - project-network

  project_mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - project-network

networks:
  project-network: