spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

admin:
  password: admin

jwt:
  secret: hello

keycloak:
  base-url: "http://localhost:5000/keycloak"
  realm: project_manager_realm
  admin-user: admin
  admin-password: admin