version: "3.7"

services:
  api_gateway:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
    ports:
      - "5000:80"
      - "5001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - project-network

  project_service:
    build:
      context: ../ProjectService
      dockerfile: ProjectAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ProjectDbSettings__ConnectionString=mongodb://project_mongo:27017
    networks:
      - project-network
    ports:
      - "5002:80" # for accessing Swagger
    depends_on:
      - project_mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project.rule=PathPrefix(`/api/v1/project`)"

  meeting_service:
    build:
      context: ../ProjectService
      dockerfile: MeetingAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - MeetingDbSettings__ConnectionString=mongodb://project_mongo:27017
    networks:
      - project-network
    ports:
      - "5003:80" # for accessing Swagger
    depends_on:
      - project_mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meeting.rule=PathPrefix(`/api/v1/meeting`)"

  todo_service:
    build:
      context: ../ProjectService
      dockerfile: ToDoAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - ToDoDbSettings__ConnectionString=mongodb://project_mongo:27017
    networks:
      - project-network
    ports:
      - "5004:80" # for accessing Swagger
    depends_on:
      - project_mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.rule=PathPrefix(`/api/v1/todo`)"

  comment_service:
    build:
      context: ../ProjectService
      dockerfile: CommentAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - CommentDbSettings__ConnectionString=mongodb://project_mongo:27017
    networks:
      - project-network
    ports:
      - "5005:80" # for accessing Swagger
    depends_on:
      - project_mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comment.rule=PathPrefix(`/api/v1/comment`)"

  project_mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - project-network

  project_rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - project-network

networks:
  project-network: