apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  ports:
  - port: 3306
    name: mysql
    targetPort: mysql
    protocol: TCP
  selector:
    app.kubernetes.io/name: mysql